### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/octopus-python/)

### ISSUE THREAD

**Issue by atheeralattar** [Picovoice/octopus#109]
### What is the URL of the doc?
https://picovoice.ai/docs/quick-start/octopus-python/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)

this line of code is missing the `metadata` arg.
`matches = octopus.search(["gorilla", "terminator"])`

should be `matches = octopus.search(metadata, ["gorilla", "terminator"])`

**Comment by kenarsa** [comment]
thank you @atheeralattar 

doc is updated.
